name: bus_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8

  # Update firebase_core to the 3.x.x series (compatible with firebase_auth >= 5.4.1)
  firebase_core: ^3.10.1  # Latest version in the 3.x.x series

  # Update firebase_auth to a version that works with firebase_core ^3.x.x
  firebase_auth: ^5.4.1  # Latest compatible version

  # You can add other Firebase dependencies here (e.g., Cloud Firestore, etc.)
  cloud_firestore: ^5.0.0 

  fluttertoast: ^8.2.12  # For showing toast messages
  
   # Make sure this is compatible with firebase_core ^3.x.x
  google_sign_in: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
